### ISSUE TITLE
Flaky frontend test - lowercased subdomain search

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/fx-private-relay#3740]
A front-end test is failing for several dependency updates:

```
FAIL src/pages/accounts/profile.test.tsx (49.192 s)
  ● The dashboard › shows that capital letters in searched-for subdomains will be lowercased

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      245 |   });
      246 |
    > 247 |   it("shows that capital letters in searched-for subdomains will be lowercased", async () => {
          |   ^
      248 |     setMockProfileDataOnce({ has_premium: true, subdomain: null });
      249 |     render(<Profile />);
      250 |

      at it (src/pages/accounts/profile.test.tsx:247:3)
      at Object.describe (src/pages/accounts/profile.test.tsx:73:1)
```

Failing in these PRs which do not touch front-end code or dependencies:

* https://github.com/mozilla/fx-private-relay/pull/3729
* https://github.com/mozilla/fx-private-relay/pull/3730

**Comment by jwhitlock** [comment]
Also fails in https://github.com/mozilla/fx-private-relay/pull/3732

**Comment by jwhitlock** [comment]
Also fails in https://github.com/mozilla/fx-private-relay/pull/3731

**Comment by jwhitlock** [comment]
Fixed in https://github.com/mozilla/fx-private-relay/pull/3752
