### ISSUE TITLE
Flaky frontend test: The dashboard allows skipping the custom domain set up during Premium onboarding

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/fx-private-relay#3741]
This test fails sometimes:

```
● The dashboard › allows skipping the custom domain set up during Premium onboarding

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      597 |   });
      598 |
    > 599 |   it("allows skipping the custom domain set up during Premium onboarding", async () => {
          |   ^
      600 |     const updateFn: ProfileUpdateFn = jest.fn();
      601 |     setMockProfileDataOnce(
      602 |       { id: 42, has_premium: true, onboarding_state: 1 },

      at it (src/pages/accounts/profile.test.tsx:599:3)
      at Object.describe (src/pages/accounts/profile.test.tsx:73:1)
```

It is failing in https://github.com/mozilla/fx-private-relay/pull/3732

**Comment by jwhitlock** [comment]
Fixed in https://github.com/mozilla/fx-private-relay/pull/3752
