### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable during invite_monitor_waitlist

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#492]
```
Sending invite email to XXXXXXXX@XXX.XXX
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/app/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/app/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/app/privaterelay/management/commands/invite_monitor_waitlist.py", line 114, in handle
    response = email_invited_user(invitee, invitation)
  File "/app/privaterelay/management/commands/invite_monitor_waitlist.py", line 68, in email_invited_user
    invitee_record.waitlists_joined['email_relay']['notified'] = True
TypeError: 'NoneType' object is not subscriptable
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
```

This could happen if there's a pre-FXA record for a Monitor user. Need to adjust the code in the script to continue past these records.

**Comment by say-yawn** [comment]
Related to this Sentry error https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/8865538/?query=is%3Aunresolved%20typeerror
